# Generated by Django 3.2.5 on 2021-08-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='adress',
            field=models.CharField(default='日本', max_length=100, verbose_name='住所'),
        ),
    ]
