# Generated by Django 3.2.5 on 2021-08-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='adress',
            field=models.CharField(max_length=100, verbose_name='住所'),
        ),
    ]
