# Generated by Django 3.2.5 on 2021-08-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='todo',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度'),
        ),
    ]
