# Generated by Django 3.2.5 on 2021-08-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210819_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='経度'),
        ),
    ]
