# Generated by Django 3.2.5 on 2021-08-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210820_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='lat',
            field=models.FloatField(verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='lng',
            field=models.FloatField(verbose_name='経度'),
        ),
    ]
