# Generated by Django 3.2.5 on 2021-08-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210824_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.IntegerField(default=2, verbose_name='ユーザーID'),
            preserve_default=False,
        ),
    ]
